import { useState, type ReactNode } from "react";
import { BrainCircuit, CalendarClock, CheckCircle2, ChevronLeft, Clock3, LayoutDashboard, Loader2, LockKeyhole, Plus, SearchCheck, ShieldCheck, Sparkles, Trash2, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type Panel = "overview" | "tasks" | "memory" | "automation" | "services";
const panels: Array<{ id: Panel; label: string; icon: typeof LayoutDashboard }> = [
  { id: "overview", label: "البداية", icon: LayoutDashboard },
  { id: "tasks", label: "مهامي", icon: CheckCircle2 },
  { id: "memory", label: "الذاكرة", icon: BrainCircuit },
  { id: "automation", label: "الأتمتة", icon: CalendarClock },
  { id: "services", label: "الخدمات", icon: LockKeyhole },
];

export function BasirAgentConsole({ onUsePrompt }: { onUsePrompt: (prompt: string) => void }) {
  const [panel, setPanel] = useState<Panel>("overview");
  const [taskTitle, setTaskTitle] = useState("");
  const [memoryText, setMemoryText] = useState("");
  const utils = trpc.useUtils();
  const showError = (error: { message?: string }) => toast.error(error.message || "حدث خطأ، حاول مرة أخرى");
  const heading = (icon: ReactNode, title: string, description: string) => <div className="mb-5 flex gap-3 border-b pb-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent">{icon}</div><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div></div>;

  const tasksQuery = trpc.basir.tasks.list.useQuery();
  const createTask = trpc.basir.tasks.create.useMutation({ onSuccess: () => { void utils.basir.tasks.list.invalidate(); setTaskTitle(""); toast.success("تم حفظ المهمة في حسابك"); }, onError: showError });
  const deleteTask = trpc.basir.tasks.delete.useMutation({ onSuccess: () => void utils.basir.tasks.list.invalidate(), onError: showError });
  const linkTask = trpc.basir.tasks.linkActivity.useMutation({ onSuccess: () => { void utils.basir.tasks.list.invalidate(); toast.success("تم تحديث ربط النشاط"); }, onError: showError });
  const activitiesQuery = trpc.activities.list.useQuery(undefined, { enabled: panel === "tasks" });
  const tasks = tasksQuery.data ?? [];
  const pendingTasks = tasks.filter((task) => !["completed", "cancelled"].includes(task.status));

  const memoriesQuery = trpc.basir.memories.list.useQuery();
  const createMemory = trpc.basir.memories.create.useMutation({ onSuccess: () => { void utils.basir.memories.list.invalidate(); setMemoryText(""); toast.success("تم حفظ الذاكرة في حسابك"); }, onError: showError });
  const setMemoryEnabled = trpc.basir.memories.setEnabled.useMutation({ onSuccess: () => void utils.basir.memories.list.invalidate(), onError: showError });
  const deleteMemory = trpc.basir.memories.delete.useMutation({ onSuccess: () => void utils.basir.memories.list.invalidate(), onError: showError });
  const memories = memoriesQuery.data ?? [];
  const activeMemories = memories.filter((memory) => memory.enabled).length;

  const automationsQuery = trpc.basir.automations.list.useQuery();
  const createAutomation = trpc.basir.automations.create.useMutation({ onSuccess: () => { void utils.basir.automations.list.invalidate(); toast.success("تم تفعيل التذكير الخاص بك"); }, onError: showError });
  const deleteAutomation = trpc.basir.automations.delete.useMutation({ onSuccess: () => void utils.basir.automations.list.invalidate(), onError: showError });
  const automations = automationsQuery.data ?? [];
  const recommendationsQuery = trpc.basir.recommendActivities.useQuery(undefined, { enabled: panel === "overview" });
  const chatPrefsQuery = trpc.basir.chatHistory.getPrefs.useQuery(undefined, { enabled: panel === "services" });
  const setChatHistory = trpc.basir.chatHistory.setEnabled.useMutation({ onSuccess: () => { void utils.basir.chatHistory.getPrefs.invalidate(); toast.success("تم تحديث إعداد سجل المحادثة"); }, onError: showError });

  const addTask = () => { const title = taskTitle.trim(); if (title) createTask.mutate({ title, requiresApproval: true }); };
  const addMemory = () => { const text = memoryText.trim(); if (text) createMemory.mutate({ text }); };
  const addAutomation = (cadence: "daily" | "weekly") => createAutomation.mutate({ title: cadence === "daily" ? "مراجعة يومية من بصير" : "ملخص أسبوعي من بصير", cadence });

  return <div className="space-y-5" dir="rtl">
    <section className="relative overflow-hidden rounded-3xl border border-accent/20 bg-gradient-to-br from-accent/15 via-background to-primary/10 p-5 md:p-7"><div className="absolute -left-8 -top-8 h-28 w-28 rounded-full bg-accent/10 blur-2xl" /><div className="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="max-w-2xl"><div className="mb-2 flex items-center gap-2 text-accent"><Sparkles className="h-5 w-5" /><span className="text-sm font-semibold">وكيل بصير الآمن</span></div><h2 className="text-2xl font-bold">من طلبك إلى خطة واضحة</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">اكتب المطلوب، يضع بصير الخطوات، ثم يطلب موافقتك قبل أي إجراء خارجي أو حساس.</p></div><Button className="gap-2" onClick={() => onUsePrompt("حلّل طلبي كوكيل: أنشئ خطة قصيرة من خطوات، وحدد ما يحتاج موافقتي قبل التنفيذ، ولا تدّع تنفيذ أي إجراء خارجي.")}><WandSparkles className="h-4 w-4" />ابدأ خطة جديدة</Button></div></section>
    <nav className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1" aria-label="أقسام وكيل بصير">{panels.map(({ id, label, icon: Icon }) => <Button key={id} variant={panel === id ? "default" : "outline"} className="shrink-0 gap-2 rounded-xl" onClick={() => setPanel(id)}><Icon className="h-4 w-4" />{label}</Button>)}</nav>
    {panel === "overview" && <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl border bg-card p-5">{heading(<WandSparkles className="h-5 w-5" />, "ماذا تريد أن يفعل بصير؟", "عرّف النتيجة المطلوبة ليقترح بصير طريقة العمل والموافقات اللازمة.")}<div className="grid gap-3 sm:grid-cols-2"><button onClick={() => onUsePrompt("رتّب لي هذه المهمة كوكيل بخطوات صغيرة قابلة للمراجعة: ")} className="rounded-2xl border p-4 text-right transition hover:border-accent hover:bg-accent/5"><CheckCircle2 className="mb-3 h-5 w-5 text-accent" /><strong className="block">تخطيط مهمة</strong><span className="mt-1 block text-xs text-muted-foreground">قسّم الطلب إلى خطوات وموافقات</span></button><button onClick={() => onUsePrompt("أريد بحثاً موثقاً. اذكر المصادر أو الخدمات التي تحتاج ربطها أولاً، ثم اقترح خطة لا تجمع بيانات خاصة ولا تنفذ أي إجراء دون موافقتي.")} className="rounded-2xl border p-4 text-right transition hover:border-accent hover:bg-accent/5"><SearchCheck className="mb-3 h-5 w-5 text-accent" /><strong className="block">بحث موثق</strong><span className="mt-1 block text-xs text-muted-foreground">راجع المصادر قبل البدء</span></button></div><div className="mt-5 rounded-xl bg-muted/60 p-4"><p className="text-sm font-semibold">الخطوة التالية</p><p className="mt-1 text-sm text-muted-foreground">{pendingTasks.length ? `لديك ${pendingTasks.length} مهام محفوظة. افتح «مهامي» لمراجعتها.` : "أضف مهمة قصيرة أو ابدأ خطة جديدة من المحادثة."}</p></div>{(recommendationsQuery.data ?? []).length > 0 && <div className="mt-4 space-y-2"><p className="text-sm font-semibold">أنشطة تناسب اهتماماتك المحفوظة</p>{recommendationsQuery.data?.map(({ activity, matchedKeywords }) => <a key={activity.id} href={`/activities/${activity.id}`} className="block rounded-xl border p-3 hover:border-accent hover:bg-accent/5"><p className="text-sm font-medium">{activity.title}</p><p className="mt-1 text-xs text-muted-foreground">يتطابق مع: {matchedKeywords.slice(0, 3).join("، ")}</p></a>)}</div>}</section><aside className="rounded-2xl border bg-card p-5">{heading(<ShieldCheck className="h-5 w-5" />, "ملخص الخصوصية", "أنت المتحكم في ما يحفظه بصير وما يُنفذ.")}<div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">مهام محفوظة</span><strong>{tasks.length}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">ذكريات مفعلة</span><strong>{activeMemories}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">خدمات مربوطة</span><strong>0</strong></div></div><p className="mt-5 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200">لا تحفظ بصير كلمات المرور، ولا تنفذ إجراءً حساساً من دون تأكيدك.</p></aside></div>}
    {panel === "tasks" && <section className="rounded-2xl border bg-card p-5">{heading(<CheckCircle2 className="h-5 w-5" />, "مهامي", "احفظ المهمة في حسابك واربطها بنشاط عند الحاجة.")}<div className="flex gap-2"><Input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} onKeyDown={(event) => event.key === "Enter" && addTask()} placeholder="مثال: جهّز ملخصاً للمقالات الجديدة" disabled={createTask.isPending} /><Button size="icon" onClick={addTask} disabled={createTask.isPending} aria-label="إضافة مهمة">{createTask.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}</Button></div><div className="mt-4 space-y-2">{tasksQuery.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">جارٍ التحميل…</p> : tasks.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">لا توجد مهام بعد.</p> : tasks.map((task) => <div key={task.id} className="rounded-xl bg-muted/50 p-3"><div className="flex items-center gap-3"><Clock3 className="h-4 w-4 text-accent" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task.title}</p><p className="text-xs text-muted-foreground">{task.status === "completed" ? "مكتملة" : task.status === "cancelled" ? "ملغاة" : task.status === "in_progress" ? "قيد التنفيذ" : task.status === "awaiting_approval" ? "بانتظار موافقتك" : "مسودة — تحتاج خطة وموافقتك"}</p></div><Button variant="ghost" size="icon" aria-label="حذف المهمة" onClick={() => deleteTask.mutate(task.id)}><Trash2 className="h-4 w-4" /></Button></div><select className="mt-2 h-8 w-full rounded-md border bg-background px-2 text-xs" value={task.linkedActivityId ?? ""} onChange={(event) => linkTask.mutate({ id: task.id, activityId: event.target.value ? Number(event.target.value) : null })} disabled={linkTask.isPending}><option value="">دون ربط بنشاط</option>{(activitiesQuery.data ?? []).map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></div>)}</div></section>}
    {panel === "memory" && <section className="rounded-2xl border bg-card p-5">{heading(<BrainCircuit className="h-5 w-5" />, "ذاكرتي مع بصير", "تفضيلات اختيارية يستخدمها بصير فقط عندما تحسن الإجابة.")}<div className="flex gap-2"><Input value={memoryText} onChange={(event) => setMemoryText(event.target.value)} onKeyDown={(event) => event.key === "Enter" && addMemory()} placeholder="مثال: أفضل الملخصات القصيرة بالعربية" disabled={createMemory.isPending} /><Button size="icon" onClick={addMemory} disabled={createMemory.isPending} aria-label="إضافة تفضيل">{createMemory.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}</Button></div><div className="mt-4 space-y-2">{memoriesQuery.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">جارٍ التحميل…</p> : memories.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">لا توجد تفضيلات محفوظة.</p> : memories.map((memory) => <div key={memory.id} className="flex items-center gap-2 rounded-xl bg-muted/50 p-3"><button className={`h-2.5 w-2.5 rounded-full ${memory.enabled ? "bg-emerald-500" : "bg-muted-foreground"}`} onClick={() => setMemoryEnabled.mutate({ id: memory.id, enabled: !memory.enabled })} aria-label="تفعيل أو إيقاف الذاكرة" /><p className="min-w-0 flex-1 text-sm">{memory.text}</p><Button variant="ghost" size="icon" aria-label="حذف الذاكرة" onClick={() => deleteMemory.mutate(memory.id)}><Trash2 className="h-4 w-4" /></Button></div>)}</div></section>}
    {panel === "automation" && <section className="rounded-2xl border bg-card p-5">{heading(<CalendarClock className="h-5 w-5" />, "الأتمتة", "تذكيرات داخل الموقع فقط، من دون بريد أو نشر أو ربط خدمة خارجية.")}<div className="flex flex-col gap-2 sm:flex-row"><Button variant="outline" className="flex-1" onClick={() => addAutomation("daily")} disabled={createAutomation.isPending}>إنشاء مراجعة يومية</Button><Button variant="outline" className="flex-1" onClick={() => addAutomation("weekly")} disabled={createAutomation.isPending}>إنشاء ملخص أسبوعي</Button></div><div className="mt-4 space-y-2">{automationsQuery.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">جارٍ التحميل…</p> : automations.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">لا توجد أتمتة مهيأة بعد.</p> : automations.map((automation) => <div key={automation.id} className="flex items-center gap-3 rounded-xl bg-muted/50 p-3"><CalendarClock className="h-4 w-4 text-accent" /><div className="flex-1"><p className="text-sm font-medium">{automation.title}</p><p className="text-xs text-muted-foreground">{automation.cadence === "daily" ? "يومياً" : "أسبوعياً"} — إشعار داخلي خاص بك فقط</p></div><Button variant="ghost" size="icon" aria-label="حذف الأتمتة" onClick={() => deleteAutomation.mutate(automation.id)}><Trash2 className="h-4 w-4" /></Button></div>)}</div></section>}
    {panel === "services" && <section className="rounded-2xl border bg-card p-5">{heading(<LockKeyhole className="h-5 w-5" />, "الخدمات والخصوصية", "تظهر هنا الاتصالات المصرح بها وإعدادات حفظ البيانات الاختيارية.")}<div className="space-y-2">{["البحث الموثق على الويب", "البريد والتقويم", "التخزين السحابي"].map((item) => <div key={item} className="flex items-center justify-between rounded-xl border p-4"><span className="text-sm font-medium">{item}</span><span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">غير مربوط</span></div>)}</div><div className="mt-4 flex items-center justify-between rounded-xl border p-4"><div><span className="block text-sm font-medium">حفظ سجل المحادثة على الخادم</span><span className="mt-0.5 block text-xs text-muted-foreground">مغلق افتراضياً. عند التفعيل يمكنك متابعة المحادثة من أجهزة أخرى.</span></div><Button size="sm" variant={chatPrefsQuery.data?.chatHistoryEnabled ? "default" : "outline"} disabled={chatPrefsQuery.isLoading || setChatHistory.isPending} onClick={() => setChatHistory.mutate({ enabled: !chatPrefsQuery.data?.chatHistoryEnabled })}>{chatPrefsQuery.data?.chatHistoryEnabled ? "مفعّل" : "مغلق"}</Button></div><div className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200"><ShieldCheck className="h-4 w-4 shrink-0" />لا تحفظ بصير كلمة مرورك، ويطلب كل إجراء خارجي حساس موافقتك النهائية.</div><button onClick={() => onUsePrompt("أريد ربط خدمة بشكل آمن. وضّح الصلاحية المطلوبة والخطوات والموافقة التي ستطلبها قبل تنفيذ أي إجراء.")} className="mt-4 flex w-full items-center justify-between rounded-xl border border-dashed p-3 text-right text-sm hover:bg-muted/50"><span>اسأل بصير عن ربط خدمة</span><ChevronLeft className="h-4 w-4 text-accent" /></button></section>}
  </div>;
}
